### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by nopuntintended** [mehedijaman/hotelio#86]
Hello,
 PHP says server started but what is the login page to access the System. Also where would the application logfiles be as the 
http://localhost:8000 gives a 500 Server Error? Thank you

**Comment by mehedijaman** [comment]
Error logs are stored in 'storage/logs/laravel.log/ file.
Make sure you properly clone the project and run composer install, and php artisan key:generate command.

**Comment by nopuntintended** [comment]
> 

Thank you and what is the User name and password to login as Admin. Does it use MySql or SQlite? Any tables etc to create before logging in? thanks

**Comment by mehedijaman** [comment]
you have to register and set your own password from register page

**Comment by nopuntintended** [comment]
Tried and getting errors and is there any Database setup part that needs to be completed?

**Comment by mehedijaman** [comment]
This is a laravel application. So you need to follow the laravel
installation process. Php artisan migrate command will setup the database
and make the tables.
